name: Automated Build from Specs

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'

env:
  # Use GitHub Secrets for sensitive values
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-cors claude-code-sdk
        
    - name: Run automated builder
      if: env.ANTHROPIC_API_KEY != ''
      run: |
        cd ${{ github.workspace }}
        python github_automated_builder.py
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        
    - name: Run tests
      run: |
        # Add your test commands here
        echo "Add test commands when tests are implemented"
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Deploy steps would go here"
        # Example: Deploy to your server
        # ssh user@server 'cd /opt/code && git pull && systemctl restart claude-web'